### ISSUE TITLE
Support for PHP

### ISSUE THREAD

**Issue by aszenz** [barklan/inline_sql_syntax#10]
In php files multi line sql is often written as 

```php
  $query = <<<SQL
      SELECT * FROM FOO WHERE FOO.bar = '1'
  SQL;
```

**Comment by barklan** [comment]
Thanks for opening issue! Added syntax highlighting for PHP strings and multiline PHP (using the format above) in v2.9.0. Leaving it open for now - please tell me if it works for your needs or if something seems weird.

**Comment by aszenz** [comment]
The built in vs code php plugin already supported syntax highlighting of sql strings for php.
What is missing is diagnostics, I see u added https://github.com/barklan/inline_sql_syntax/issues/22, so feel free to close this issue
