### ISSUE TITLE
Extension randomly popped up a message that just says "fuck!"

### ISSUE THREAD

**Issue by 19007361** [barklan/inline_sql_syntax#28]
![Screenshot 2022-04-08 at 22 42 16](https://user-images.githubusercontent.com/15359231/162527389-dbc2b035-ade2-4a74-9301-7d69ac6374ad.png)

I'm not joking

**Comment by barklan** [comment]
Yes, really sorry about that))) - should be fine with v2.10.3. I really need to take this extension seriously and use separate debug output.

**Comment by 19007361** [comment]
No worries, I have definitely done that and hopefully not forgotten to remove in prod 😁
